version: '3'

services:
  omc.dockerapi:
    image: omc.dockerapi
    build:
      context: ./OMC.DockerApi
      dockerfile: Dockerfile
    depends_on:
      - mssql
  mssql:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"