version: '3'

services:
  omc.dockerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "80"
  mssql:
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - C:\Users\VivienFABING\Desktop\mytestvolume:/var/opt/mssql
    ports:
      - "1433:1433"
  angular:
    build:
      args:
        source: obj/Docker/empty/
    volumes:
      - .\docker-angular:/app
    ports:
      - "4200:4200"
