version: '3'

services:
  omc.dockerapi:
    image: omc.dockerapi
    build:
      context: ./OMC.DockerApi
      dockerfile: Dockerfile
    depends_on:
      - mssql
  mssql:
    image: "microsoft/mssql-server-linux"
    expose:
      - "1433"
  angular:
    image: docker-angular
    build:
      context: ./docker-angular
    depends_on:
      - omc.dockerapi